[workspace]
members = [".", "capi", "tools"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "BSD-2-Clause"
repository = "https://github.com/halidecx/wpd"

[package]
name = "wpd"
description = "A fast WebP decoder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
links = "wpdasm"
exclude = ["*.c", "*.h", "meson*", "scripts/", "tests/", "tools/", "wpd-test-data/"]

[lib]
crate-type = ["rlib"]

[features]
default = ["asm"]
asm = []
trim_dsp = []
force_rac32 = []

[build-dependencies]
cc = "1"
nasm-rs = { version = "0.3", features = ["parallel"] }

[dependencies]
zerocopy = { version = "0.8", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"

[profile.minsize]
inherits = "release"
opt-level = "s"

[profile.release.package."*"]
opt-level = 3

[profile.debugopt]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true
lto = false
codegen-units = 16
