[package]
name = "wpd-capi"
description = "C ABI for the wpd WebP decoder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "wpd_capi"
crate-type = ["staticlib", "rlib"]

[dependencies]
wpd = { path = "..", default-features = false }

[features]
default = ["asm"]
asm = ["wpd/asm"]
trim_dsp = ["wpd/trim_dsp"]
force_rac32 = ["wpd/force_rac32"]
