#ifndef FFVP8_AARCH64_ASM_CONFIG_H
#define FFVP8_AARCH64_ASM_CONFIG_H
#define CONFIG_PIC 1
#define HAVE_AS_FUNC 0
#define HAVE_AS_ARCH_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_AES_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_CRC_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_DOTPROD_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_I8MM_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SHA3_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME_I16I64_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME2_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SVE_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SVE2_DIRECTIVE 0
#define HAVE_SECTION_DATA_REL_RO 0
#define HAVE_SME 0
#define EXTERN_ASM
#endif
