#ifndef WPD_AARCH64_ASM_CONFIG_H
#define WPD_AARCH64_ASM_CONFIG_H
#define CONFIG_PIC 1
#define HAVE_AS_FUNC 0
#define HAVE_AS_ARCH_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_AES_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_CRC_DIRECTIVE 0
#ifndef HAVE_AS_ARCHEXT_DOTPROD_DIRECTIVE
#define HAVE_AS_ARCHEXT_DOTPROD_DIRECTIVE 0
#endif
#ifndef HAVE_AS_ARCHEXT_I8MM_DIRECTIVE
#define HAVE_AS_ARCHEXT_I8MM_DIRECTIVE 0
#endif
#define HAVE_AS_ARCHEXT_SHA3_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME_I16I64_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME2_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SVE_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SVE2_DIRECTIVE 0
#define HAVE_SME 0
#ifndef HAVE_DOTPROD
#define HAVE_DOTPROD 0
#endif
#ifndef HAVE_I8MM
#define HAVE_I8MM 0
#endif
#ifdef __APPLE__
#define EXTERN_ASM _
#else
#define EXTERN_ASM
#endif
#endif
